name: Deploy Cloudflare Worker
on:
  push:
    branches: [main] # 监听 main 分支的推送事件

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install Wrangler
        run: npm install -g @cloudflare/wrangler

      - name: Authenticate Wrangler
        env:
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
        run: wrangler login --api-token $CF_API_TOKEN

      - name: Deploy Worker
        run: wrangler publish --project-name firsttest
